# https://www.home-assistant.io/integrations/default_config/
default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

debugpy:
  start: true
  wait: false
  port: 5678

go2rtc:
  url: http://localhost:1984

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.wiser_by_feller: debug

# Adds Log Viewer to the sidebar
panel_custom:
  - name: logs
    sidebar_title: Logs
    sidebar_icon: mdi:math-log
    url_path: "config/logs"
    js_url: /api/hassio/app/entrypoint.js
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator
  - name: wiser-integration
    sidebar_title: Wiser by Feller
    sidebar_icon: mdi:lightbulb
    url_path: "config/integrations/integration/wiser_by_feller"
    js_url: /api/hassio/app/entrypoint.js
    embed_iframe: true
  - name: actions
    sidebar_title: Actions
    sidebar_icon: mdi:gesture-tap
    url_path: "config/developer-tools/action"
    js_url: /api/hassio/app/entrypoint.js
    embed_iframe: true
